jwt support was added
MaxSkory/basic-authentication pull request #2
Opened 2023-11-19 13:30 UTC by MaxSkory

2023-11-19 13:39 UTC, MaxSkory commented
Зробив окремий репо, тому, що це новий розділ, а я вже пройшов spring security.
https://github.com/MaxSkory/online-book-store

2023-11-19 18:06 UTC, Sanderfuck requested changes

2023-11-19 18:06 UTC, Sanderfuck commented on src/main/java/mskory/base/authentication/exception/JwtParsingException.java
> +}
Do you need 3 custom exception? You can use different messages for one custom

2023-11-19 18:06 UTC, Sanderfuck commented on src/main/java/mskory/base/authentication/security/CustomUserDetailService.java
> +    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
Why you throws?

2023-11-19 18:06 UTC, Sanderfuck commented on src/main/java/mskory/base/authentication/security/JwtAuthenticationFilter.java
> +        return null;
Return null is bad approach

2023-11-19 18:06 UTC, Sanderfuck commented on src/main/resources/application.properties
> +jwt.token.expiration-time=30
Is it enough?

2023-11-19 20:52 UTC, MaxSkory commented on src/main/resources/application.properties
> +jwt.token.expiration-time=30
30 minutes is not enough?

2023-11-20 12:01 UTC, okuzan commented on src/main/resources/application.properties
> +jwt.token.expiration-time=30
I believe it's 30 seconds

2023-11-20 13:42 UTC, MaxSkory commented on src/main/resources/application.properties
> +jwt.token.expiration-time=30
<img width="731" alt="Знімок екрана 2023-11-20 о 15 38 34" src="https://github.com/MaxSkory/basic-authentication/assets/25840669/931fef46-5944-409c-b52f-cae3858d85d4">

2023-11-20 13:42 UTC, merged